webaplication/drag_drop/urls.py
from argparse import Namespace
from django.urls import path
from . import views

app_name = 'drag_drop'

urlpatterns = [
    path('', views.upload_file , name='drag_drop_screen')
]

webaplication/login/urls.py
from xml.etree.ElementInclude import include
from django.urls import path, include
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.login_user, name='login_user'),
    path('logout_user/', views.logout_user, name='logout_user'),
    
    path('inside/', views.inside, name='inside')
]

webaplication/regdiario/urls.py
from django.urls import path
from regdiario import views

app_name = 'reg_diario'

urlpatterns = [
    path('', views.pacients_list, name='pacients_list'),
    path('phase/<int:pacient_id>/', views.phases_list, name='phases_list')
]

webaplication/webaplication/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),

    #Log In App.
    path('', include('django.contrib.auth.urls')),
    path('', include('login.urls')),

    #App->Registro diario
    path('regdiario/', include('regdiario.urls')),

    #App->Drag&Drop
    path('drag_drop/', include('drag_drop.urls'))

]

webaplication/drag_drop/models.py
from django.db import models

# Create your models here.

webaplication/login/models.py
from django.db import models

# Create your models here.

webaplication/regdiario/models.py
from django.db import models

# Create your models here.
class Pacient(models.Model):
    name = models.CharField(max_length=100)
    age  = models.IntegerField()

    def __str__(self):
        return self.name

class Phase(models.Model):
    pacient = models.ForeignKey('Pacient', on_delete=models.CASCADE)
    name    = models.CharField(max_length=100)
    number  = models.IntegerField()

    def __str__(self):
        return str(self.number)

class Day(models.Model):
    phase  = models.ForeignKey('Phase', on_delete=models.CASCADE)
    number = models.IntegerField()
    date   = models.DateTimeField()

    def __str__(self):
        return str(self.number)

class Track(models.Model):
    day      = models.ForeignKey('Day', on_delete=models.CASCADE)
    number   = models.IntegerField()
    duration = models.TimeField(auto_now=False, auto_now_add=False, default=0)

    def __str__(self):
        return str(self.number)

class Note(models.Model):
    track = models.ForeignKey('Track', on_delete=models.CASCADE)
    number = models.IntegerField(default=0)
    note  = models.TextField()

    def __str__(self):
        return str(self.number)

webaplication/drag_drop/forms.py
from django import forms

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.forms.FileField()

webaplication/drag_drop/views.py
from django.http import HttpResponseRedirect 
from django.shortcuts import render, redirect
from .forms import UploadFileForm
from .processfiles import handle_uploaded_file #Function for file process
from django.core.files.storage import FileSystemStorage
from django.contrib import messages
from django.conf import settings

# Create your views here.
def upload_file(request):
    #Si el usuario está autenticado:
    if request.user.is_authenticated:
        if request.method == 'POST' and request.FILES['First_File']:
            print(request.FILES)
            myfile = request.FILES['First_File']
            print("Nombre del archivo cargado: {}".format(myfile.name))
            fs = FileSystemStorage()
            filename = fs.save(myfile.name, myfile)
            uploaded_file_url = fs.url(filename)
            
            messages.success(request, 'El archivo fue cargado en la ruta: drag_drop/media{}'.format(uploaded_file_url))
            return render(request, 'drag_drop/loadfileform.html', { 'uploaded_file_url': uploaded_file_url })
        
        return render(request, 'drag_drop/loadfileform.html')
    
    #Si el usuario no está autenticado, redirecciona a la pagina de LOG IN:
    else:
        return redirect('login:login_user')

webaplication/login/views.py
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib import messages


# Create your views here.
def inside(request):
    return render(request, 'login/prueba.html', {})

def logout_user(request):
    auth_logout(request)
    messages.success(request, "Saliste exitosamente")
    return redirect('login:login_user')

def login_user(request):

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            auth_login(request, user)
            # Redirect to a success page.
            #messages.success(request, 'Hubo un error on el Log In, intente de nuevo.')
            #return redirect('login:inside')
            return redirect('drag_drop:drag_drop_screen')
            #return redirect('reg_diario:pacients_list')
        else:
            # Return an 'invalid login' error message.
            messages.success(request, 'Usuario o contraseña son incorrectos !!!')
            return redirect('login:login_user')
    else:
        return render(request, 'login/login.html', {})

webaplication/regdiario/views.py
from multiprocessing import context
from django.shortcuts import render, HttpResponse

from .models import Pacient, Phase

# Create your views here.
def pacients_list(request):
    #return HttpResponse('Aplicación registro diario')
    pacients_list = Pacient.objects.all()
    context = {'pacients': pacients_list}
    return render(request, 'regdiario/pacients_list.html', context)

def phases_list(request, pacient_id):
    pacient = Pacient.objects.get(pk=pacient_id)
    context = {'pacient': pacient}
    return render(request, 'regdiario/phases_list.html', context)

webaplication/drag_drop/templates/drag_drop/loadfileform.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Upload Files</title>
    <link rel="icon" type="image/x-icon" href="{% static 'drag_drop/images/turn_on.jpg' %}">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<body>

    {% if  user.is_authenticated%}
        <!--nav BAR ZONE-->
        <nav class="navbar navbar-expand-md navbar-light pt-3 px-5 shadow">
            <div class="container-xxl">
                <a href="#drag_drop" class="navbar-brand">
                    <span class="fw-bold text-secondary">Upload Files</span>
                </a>

                <!-- toggle button for mobile nav-->
                <button class="navbar-toggler" 
                        type="button" 
                        data-bs-toggle="collapse" 
                        data-bs-target="#main-nav" 
                        aria-controls="main-nav" 
                        aria-expanded="false" 
                        aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>    
                </button>


                <!-- navbar links -->
                <div class="collapse navbar-collapse justify-content-end align-center" id="main-nav">
                    <ul class="navbar-nav">
                        
                        <li class="nav-item ">
                            <a class="nav-link text-decoration-underline"> usuario: {{user}}</a>
                        </li>

                        <li class="nav-item"> <!--se muestra de medio en adelante-->
                            <a href="{% url 'login:logout_user'%}" class="btn btn-outline-secondary">Sign out</a>
                        </li>                    

                    </ul>
                </div>

            </div>
        </nav>



        <!--UpLoad ZONE-->
        <div class="container mt-5 shadow">
            <h2 class="Display-1">Upload Files</h2>
            <p class="text-muted">This section will be used to upload your files.</p>
        </div>

        <div class="container justify-content-center align-items-center">
            <div class="row border border-secondary rounded">
                <div class="col-6">
                    <div class="m-2">
                        <form action="{% url 'drag_drop:drag_drop_screen'%}" enctype="multipart/form-data" method="POST">
                            {% csrf_token %}
                            <div class="mb-3">
                            <label id="myfile" class="form-label">First File</label>
                            <input type="file" class="form-control" name="First_File" aria-describedby="emailHelp">
                            <div id="emailHelp" class="form-text">Select your file.</div>
                            </div>
                            <button type="submit" class="btn btn-success">Upload</button>
                        </form>
                    </div>
                </div>

                <!--div class="col-6">
                    <div class="m-2">
                        <form enctype="multipart/form-data" method="POST">
                            <div class="mb-3">
                            <label id="myfile" class="form-label">Second File</label>
                            <input type="file" class="form-control" id="first_file" aria-describedby="emailHelp">
                            <div id="emailHelp" class="form-text">Select your file.</div>
                            </div>
                            <button type="submit" class="btn btn-primary">Upload</button>
                        </form>
                    </div>
                </div-->
            </div>

            {% if messages %}
                {% for message in messages %}
                    
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <strong>Carga de Archivo: </strong>{{message}}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    
                {% endfor %}
            {% endif %}
        </div>
        
        

    {% else %}
        <h1 class="bg-danger">El usuario es {{user}}</h1>
    {% endif %}

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>
</html>

webaplication/login/templates/login/login.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title>Upload Formats App</title>
    <link rel="icon" type="image/x-icon" href="{% static 'login/images/turn_on.jpg' %}">

    <!-- JavaScript Bundle with Popper -->
    <script src="{% static 'login/js/bootstrap.bundle.min.js'%}" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    
    <!-- CSS Bundle Bootstrap -->
    <link href="{% static 'login/assets/dist/css/bootstrap.min.css'%}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }      
    </style>

    <!-- Custom styles for this template -->
    <link href="{% static 'login/css/signin.css' %}" rel="stylesheet">
  
  </head>
   
  <body class="text-center">
    
  <main class="form-signin w-100 m-auto">

  
    {% if messages %}
        {% for message in messages %}
            
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>Autenticación: </strong>{{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            
        {% endfor %}
    {% endif %}

    <form action="" method="POST">
      {% csrf_token %}
        <img class="mb-4 shadow-lg rounded-circle" src="{% static 'login/images/turn_on.jpg' %}" alt="" width="200" height="200">
        <h1 class="h3 mb-3 fw-normal">Please Sign In</h1>
                
        <div class="form-floating">
            <input type="text" name="username" class="form-control text-center" id="floatingInput" placeholder="name@example.com">
            <label class="text-center"for="floatingInput">Username</label>
        </div>
        <div class="form-floating">
            <input type="password" name="password" class="form-control text-center" id="floatingPassword" placeholder="Password">
            <label class="text-center" for="floatingPassword">Password</label>
        </div>
       
        <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
        
        <p class="mt-5 mb-3 text-muted">&copy; 2020-Current</p>
    </form>
  </main>


  </body>
</html>

webaplication/regdiario/templates/regdiario/pacients_list.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title>Tomatis App</title>
    <link rel="icon" type="image/x-icon" href="{% static 'login/images/fondo_tomatis.png' %}">

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/sign-in/">
    
    <!-- JavaScript Bundle with Popper -->
    <script src="{% static 'login/js/bootstrap.bundle.min.js'%}" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    
    <!-- CSS Bundle Bootstrap -->
    <link href="{% static 'login/assets/dist/css/bootstrap.min.css'%}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }      
    </style>

    <!-- Custom styles for this template -->
    <link href="{% static 'login/css/signin.css' %}" rel="stylesheet">
  
  </head>
 
  <!--Sección NavBar-->
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Features</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown link
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!---->


  <body class="text-center">
    
    <div class="container">
      contenido1
    </div>
    <div class="container">
      contenido2
    </div>

  
    <main class="form-signin w-100 m-auto">
  
    

    <h1>Nuestros Tomatis:</h1>
      <table class="table table-hover">
          <thead>
              <tr>
                <th scope="col">Name</th>
                <th scope="col">Age</th>
              </tr>
          </thead>

          {% if pacients %}
            <tbody>
              {% for pacient in pacients %}
                  <tr>
                  <th scope="row"><a href= "{% url 'reg_diario:phases_list' pacient.id %}">{{pacient.name}}</a></th>
                  <td>{{pacient.age}}</td>
                  </tr>
              {% endfor %}
            </tbody>
            {% endif %}
      </table>
  </main>


  </body>
</html>

webaplication/regdiario/templates/regdiario/phases_list.html
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>


{% if pacient %}
<h1>{{pacient.name}}</h1>
{% endif %}

<table class="table table-hover">
    <thead>
        <tr>
          <th scope="col">Phase Number</th>
          <th scope="col">Phase Name</th>
        </tr>
    </thead>

    {% if pacient %}
      <tbody>
        {% for phase in pacient.phase_set.all %}
            <tr>
            <th scope="row">{{phase.number}}</th>
            <td><a href= "{% url 'reg_diario:phases_list' pacient.id %}">{{phase.name}}</a></td>
            </tr>
        {% endfor %}
      </tbody>
      {% endif %}
</table>